name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Cordova
      run: npm install -g cordova

    - name: Install dependencies
      run: npm install

    - name: Add Android platform
      run: cordova platform add android

    - name: Build Android APK
      run: cordova build android

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: snappfood-auth-app
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
